### PR TITLE
Small edits

### PR DESCRIPTION
**Pull request by mblue9**
Hi Luciane,

I just made some small edits as per the IUC standards here (see what you think): https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/integration_checklist.rst

I also removed some requirements that didn't look like they were used.

I haven't managed to get planemo test working with this on my Mac yet as I get the segmentation fault error below, even with just loading library(NanoStringNorm) in R in the conda env (may be a Mac-specific issue):

`
|  16: library(NanoStringNorm)
|  An irrecoverable exception occurred. R is aborting now ...
|  /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/job_working_directory/000/3/tool_script.sh: line 169: 14178 Segmentation fault: 11  Rscript --default-packages=methods,utils /Users/doylemaria/galaxy/nanostringnorm/nanonorm.R --rccfile "/private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/files/000/dataset_1.dat" --output /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/files/000/dataset_3.dat --outpdf /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/files/000/dataset_5.dat --codecount none --background none --samplecont none --othernorm none --boxplot /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/files/000/dataset_8.dat --controls /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/files/000/dataset_6.dat --househk /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/files/000/dataset_7.dat --trait /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/files/000/dataset_2.dat --statistic /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpLNg8E7/files/000/dataset_4.dat
`

Maria

### CODE REVIEW

**Comment by bgruening** [comment]
Hi @sussuchi and @mblue9!

These changes look good to me!

**Comment by mblue9** [comment]
Thanks @bgruening ! I still can't get planemo test to run with this tool on my Mac. I tried deleting the env again but still getting same error as above when `library(NanoStringNorm)` is run. I've these packages:
```
    bioconductor-affy:           1.56.0-r3.4.1_0        bioconda   
    bioconductor-affyio:         1.48.0-r3.4.1_0        bioconda   
    bioconductor-biobase:        2.38.0-r3.4.1_0        bioconda   
    bioconductor-biocgenerics:   0.24.0-r3.4.1_0        bioconda   
    bioconductor-biocinstaller:  1.28.0-r3.4.1_0        bioconda   
    bioconductor-limma:          3.34.9-r3.4.1_0        bioconda   
    bioconductor-preprocesscore: 1.40.0-r3.4.1_0        bioconda   
    bioconductor-vsn:            3.46.0-r3.4.1_0        bioconda   
    bioconductor-zlibbioc:       1.24.0-r3.4.1_0        bioconda   
    ca-certificates:             2018.4.16-0            conda-forge
    cairo:                       1.14.12-he56eebe_3     conda-forge
    curl:                        7.60.0-h93b3f91_0      conda-forge
    fontconfig:                  2.13.0-h074f895_3      conda-forge
    freetype:                    2.8.1-0                conda-forge
    gettext:                     0.19.8.1-0             conda-forge
    glib:                        2.55.0-0               conda-forge
    graphite2:                   1.3.11-h7d4d677_0      conda-forge
    gsl:                         2.1-2                  conda-forge
    harfbuzz:                    1.8.4-h2bb21d5_0       conda-forge
    icu:                         58.2-hfc679d8_0        conda-forge
    jpeg:                        9c-h470a237_0          conda-forge
    krb5:                        1.14.6-0               conda-forge
    libffi:                      3.2.1-1                bioconda   
    libgcc:                      4.8.5-1                           
    libgfortran:                 3.0.0-0                conda-forge
    libiconv:                    1.15-h470a237_1        conda-forge
    libpng:                      1.6.34-ha92aebf_1      conda-forge
    libssh2:                     1.8.0-h5b517e9_2       conda-forge
    libtiff:                     4.0.9-he6b73bb_1       conda-forge
    libxml2:                     2.9.8-h422b904_2       conda-forge
    ncurses:                     6.1-0                  conda-forge
    openssl:                     1.0.2o-0               conda-forge
    pango:                       1.40.14-h9105a7a_2     conda-forge
    pcre:                        8.41-1                 conda-forge
    pixman:                      0.34.0-2               conda-forge
    r-assertthat:                0.2.0-r3.4.1_0         conda-forge
    r-base:                      3.4.1-hff14c37_6       conda-forge
    r-cli:                       1.0.0-r3.4.1_0         conda-forge
    r-colorspace:                1.3_2-r3.4.1_0         conda-forge
    r-crayon:                    1.3.4-r3.4.1_0         conda-forge
    r-dichromat:                 2.0_0-r3.4.1_0         conda-forge
    r-digest:                    0.6.15-r3.4.1_0        conda-forge
    r-gdata:                     2.18.0-r3.4.1_0        conda-forge
    r-getopt:                    1.20.2-r3.4.1_0        conda-forge
    r-ggplot2:                   3.0.0-r341h6115d3f_0   conda-forge
    r-glue:                      1.3.0-r341_0           conda-forge
    r-gtable:                    0.2.0-r3.4.1_0         conda-forge
    r-gtools:                    3.8.1-r341_0           conda-forge
    r-labeling:                  0.3-r3.4.1_0           conda-forge
    r-lattice:                   0.20_34-r3.4.1_0       conda-forge
    r-lazyeval:                  0.2.1-r3.4.1_0         conda-forge
    r-magrittr:                  1.5-r3.4.1_0           conda-forge
    r-mass:                      7.3_50-r341hc070d10_1  conda-forge
    r-matrix:                    1.2_14-r3.4.1_0        conda-forge
    r-mgcv:                      1.8_24-r341_0          conda-forge
    r-munsell:                   0.5.0-r341_0           conda-forge
    r-nanostringnorm:            1.1.21-r341_2          bioconda   
    r-nlme:                      3.1_131-r3.4.1_0       conda-forge
    r-pillar:                    1.2.2-r341h6115d3f_1   conda-forge
    r-plyr:                      1.8.4-r3.4.1_0         conda-forge
    r-r6:                        2.2.2-r3.4.1_0         conda-forge
    r-rcolorbrewer:              1.1_2-r3.4.1_0         conda-forge
    r-rcpp:                      0.12.17-r341h9d2a408_0 conda-forge
    r-reshape2:                  1.4.3-r3.4.1_0         conda-forge
    r-rlang:                     0.2.1-r341_0           conda-forge
    r-scales:                    0.5.0-r3.4.1_0         conda-forge
    r-stringi:                   1.2.3-r341_0           conda-forge
    r-stringr:                   1.3.1-r341_0           conda-forge
    r-tibble:                    1.4.2-r3.4.1_0         conda-forge
    r-utf8:                      1.1.3-r3.4.1_0         conda-forge
    r-viridislite:               0.3.0-r3.4.1_0         conda-forge
    r-withr:                     2.1.1-r3.4.1_0         conda-forge
    r-writexls:                  4.0.0-r3.4.1_0         conda-forge
    readline:                    7.0-haf1bffa_1         conda-forge
    tk:                          8.6.8-0                conda-forge
    xz:                          5.2.3-0                conda-forge
    zlib:                        1.2.11-h470a237_3      conda-forge
```

**Comment by sussuchi** [comment]
Hi @mblue9 and @bgruening, thank you very much for all your assistance in GCCBOSC and CoFest! I will check the test files and set input and ouput files to csv format.

**Comment by mblue9** [comment]
Just to let you know in case this ever affects you, I found out why I was getting that segmentation fault error above. My local R packages were being preferentially used instead of the ones in the conda env, which I could see in R with .libPaths(). If I moved these directories below out of the path
```
/Users/maria/Library/R/3.4/library
/Library/Frameworks/R.framework/Versions/3.4/Resources/library
```
then just the env R library is used e.g.:
```
/Users/maria/miniconda3/envs/mulled-v1-5e3b8685e72dc7432cdca73af39caf7089433c9ea8d67d3d70bacf877247fd8c/lib/R/library
```
Seems a bit weird to me as I thought only the env R library would be used.

**Comment by bgruening** [comment]
@mblue9 this is a known R issue :( R is searching actively in your HOME dir for the R folder and prefers this instead :(
Glad you figured it out!

**Comment by mblue9** [comment]
Ah ok thanks @bgruening! So it's a known issue, just not known to me 😄 What's the best way to have my local R packages and the conda ones not interfering with each other? As I ended up moving those folders out of the way. Will I just have to move them out and back every time I need to switch between testing packages and using R on my laptop?

**Comment by bgruening** [comment]
Thats what I do as well. I'm not aware of a better way. That said there is imho no reason to keep the local R installation, as you can package.install() in the conda environment as well.

**Comment by mblue9** [comment]
Ok thanks, would the  package.install() method work with RStudio? As if I'm using R on my laptop it's with RStudio.
Btw I'm just amazed that I never ran into this issue before as I've been working on/testing R tools for months and only had that issue for the first time at GCC. Was I just lucky 😃

**Pull request merged**
